import { brandText } from "../config/brand.js";import React, { useEffect, useMemo, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { get, post } from './api.js';

const money = (n) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(n || 0));
const csvCell = (v) => `"${String(v ?? '').replaceAll('"', '""')}"`;
function downloadCsv(rows, name) {if (!rows?.length) return;const keys = Object.keys(rows[0]);const text = [keys.map(csvCell).join(','), ...rows.map((r) => keys.map((k) => csvCell(r[k])).join(','))].join('\r\n');const a = document.createElement('a');a.href = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' }));a.download = name;a.click();URL.revokeObjectURL(a.href);}
function parseCsv(text) {const rows = [];let row = [],cell = '',q = false;for (let i = 0; i < text.length; i++) {const c = text[i],n = text[i + 1];if (c === '"' && q && n === '"') {cell += '"';i++;} else if (c === '"') q = !q;else if (c === ',' && !q) {row.push(cell);cell = '';} else if ((c === '\n' || c === '\r') && !q) {if (c === '\r' && n === '\n') i++;row.push(cell);cell = '';if (row.some((x) => x !== '')) rows.push(row);row = [];} else cell += c;}if (cell || row.length) {row.push(cell);rows.push(row);}if (rows.length < 2) return [];const h = rows[0].map((x) => x.trim());return rows.slice(1).map((r) => Object.fromEntries(h.map((k, i) => [k, r[i] ?? ''])));}

function Table({ rows, cols }) {return <div className="table-wrap"><table><thead><tr>{cols.map((c) => <th key={c.k}>{c.l}</th>)}</tr></thead><tbody>{rows?.length ? rows.map((r, i) => <tr key={r.row_id || r.id_inventario || r.id_movimiento || i}>{cols.map((c) => <td key={c.k}>{c.f ? c.f(r[c.k], r) : String(r[c.k] ?? '')}</td>)}</tr>) : <tr><td colSpan={cols.length} className="empty">Sin registros</td></tr>}</tbody></table></div>;}

export default function TCGOperationsPage() {
  const [tab, setTab] = useState('inventario'),[branches, setBranches] = useState([]),[branch, setBranch] = useState(''),[inventory, setInventory] = useState([]),[moves, setMoves] = useState([]),[counts, setCounts] = useState([]),[sales, setSales] = useState([]),[msg, setMsg] = useState(''),[error, setError] = useState(''),[busy, setBusy] = useState(false),[q, setQ] = useState('');
  const [cart, setCart] = useState([]),[scan, setScan] = useState(''),[countId, setCountId] = useState('');
  const fileRef = useRef();
  const branchName = branches.find((x) => x.id_sucursal === branch)?.nombre || branch;
  const total = useMemo(() => cart.reduce((s, x) => s + Number(x.precio || 0) * Number(x.cantidad || 0), 0), [cart]);
  const run = async (fn) => {setBusy(true);setError('');setMsg('');try {return await fn();} catch (e) {setError(e.message);} finally {setBusy(false);}};
  async function reload() {await run(async () => {const [b, i, m, c, s] = await Promise.all([get('/branches'), get(`/inventory?q=${encodeURIComponent(q)}&branch=${encodeURIComponent(branch)}`), get(`/movements?branch=${encodeURIComponent(branch)}`), get('/counts?limit=100'), get('/sales?limit=100')]);setBranches(b);setInventory(i);setMoves(m);setCounts(c);setSales(s);if (!branch && b[0]) setBranch(b[0].id_sucursal);});}
  useEffect(() => {reload();}, []);useEffect(() => {if (branch) run(async () => {setInventory(await get(`/inventory?q=${encodeURIComponent(q)}&branch=${encodeURIComponent(branch)}`));setMoves(await get(`/movements?branch=${encodeURIComponent(branch)}`));});}, [branch]);
  const admin = { idAdmin: 'LOCAL', administrador: 'Administrador Local' };
  async function adjust(idInventario, delta) {await run(async () => {await post('/adjust', { idInventario, idSucursal: branch, delta: Number(delta), motivo: 'Ajuste Fase 10.3', ...admin });setMsg('Ajuste aplicado.');await reload();});}
  async function transfer() {const idInventario = prompt('ID Inventario TCG');if (!idInventario) return;const dest = prompt('ID sucursal destino');if (!dest) return;const cantidad = Number(prompt('Cantidad', '1'));await run(async () => {await post('/transfer', { idInventario, idSucursalOrigen: branch, idSucursalDestino: dest, cantidad, motivo: 'Transferencia Fase 10.3', ...admin });setMsg('Transferencia completada.');await reload();});}
  function addCart(r) {setCart((c) => {const x = c.find((v) => v.idInventario === r.id_inventario);if (x) return c.map((v) => v === x ? { ...v, cantidad: v.cantidad + 1 } : v);return [...c, { idInventario: r.id_inventario, sku: r.sku, carta: r.carta, precio: Number(r.precio_oferta || r.precio || 0), cantidad: 1 }];});}
  async function sale() {if (!cart.length) return;await run(async () => {const r = await post('/sales', { idSucursal: branch, sucursal: branchName, items: cart, metodoPago: 'EFECTIVO', ...admin });setMsg(`Venta ${r.idVenta} completada · ${money(r.total)}`);setCart([]);await reload();});}
  async function doScan(action = 'ENTRADA') {if (!scan.trim()) return;await run(async () => {const r = await post('/scan', { codigo: scan.trim(), accion: action, idSucursal: branch, cantidad: 1, ...admin });setMsg(`Escaneo ${r.idEscaneo}: ${r.inventario?.sku || scan}`);setScan('');await reload();});}
  async function newCount() {await run(async () => {const r = await post('/counts', { idSucursal: branch, notas: 'Conteo Fase 10.3', ...admin });setCountId(r.idConteo);setMsg(`Conteo ${r.idConteo} abierto.`);setCounts(await get('/counts?limit=100'));});}
  async function capture() {const inv = prompt('ID Inventario');if (!inv) return;const n = Number(prompt('Cantidad física', '0'));await run(async () => {await post(`/counts/${countId}/capture`, { idInventario: inv, cantidadFisica: n, ...admin });setMsg('Captura registrada.');});}
  async function closeCount() {if (!countId) return;const apply = confirm('¿Aplicar ajustes al stock al cerrar?');await run(async () => {await post(`/counts/${countId}/close`, { aplicarAjustes: apply, ...admin });setMsg('Conteo cerrado.');setCountId('');await reload();});}
  async function labels() {const selected = inventory.slice(0, Math.min(30, inventory.length));if (!selected.length) return;const w = window.open('', '_blank');let html = brandText("<html><head><title>Etiquetas Shiny TCG</title><style>body{font-family:Arial}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.l{border:1px solid #222;padding:8px;break-inside:avoid}img{width:90px;height:90px}.s{font-size:11px}</style></head><body><div class=\"grid\">");for (const r of selected) {const qr = await QRCode.toDataURL(brandText(`Shiny:TCG:${r.id_inventario}`), { margin: 1, width: 180 });html += `<div class="l"><b>${r.carta || r.sku || r.id_inventario}</b><br><img src="${qr}"><div class="s">${r.sku || ''}<br>${r.id_inventario}<br>${r.rareza || ''} · ${r.condicion || ''}</div></div>`;}html += '</div><script>window.onload=()=>window.print()</script></body></html>';w.document.write(html);w.document.close();}
  async function exportKind(kind) {await run(async () => {const rows = await get(`/export/${kind}?limit=10000`);downloadCsv(rows, `SHINY_TCG_${kind}_${new Date().toISOString().slice(0, 10)}.csv`);setMsg(`${rows.length} registros exportados.`);});}
  async function importBulk(file) {if (!file) return;const rows = parseCsv(await file.text()).map((r) => ({ tipo: (r.tipo || r.accion || 'AJUSTE').toUpperCase(), idInventario: r.idInventario || r.id_inventario, idSucursal: r.idSucursal || r.id_sucursal || branch, idSucursalOrigen: r.idSucursalOrigen || r.id_sucursal_origen || branch, idSucursalDestino: r.idSucursalDestino || r.id_sucursal_destino, delta: Number(r.delta || r.cantidad || 0), cantidad: Number(r.cantidad || 0), motivo: r.motivo || 'Importación bulk 10.3' }));await run(async () => {const out = await post('/bulk', { rows, ...admin });setMsg(`Bulk: ${out.ok} OK / ${out.error} error(es).`);await reload();});fileRef.current.value = '';}
  const colsInv = [{ k: 'sku', l: 'SKU' }, { k: 'carta', l: 'Carta' }, { k: 'rareza', l: 'Rareza' }, { k: 'condicion', l: 'Cond.' }, { k: 'stock_sucursal', l: 'Stock suc.' }, { k: 'stock_global', l: 'Global' }, { k: 'precio', l: 'Precio', f: money }, { k: 'id_inventario', l: 'ID' }];
  return <div className="app"><header><div><h1>{brandText("Shiny · TCG Operaciones")}</h1><p>Fase Local 10.3 · PostgreSQL</p></div><div className="status">{busy ? 'Procesando…' : 'LOCAL CRUD'}</div></header>
 <section className="toolbar"><label>Sucursal <select value={branch} onChange={(e) => setBranch(e.target.value)}><option value="">Todas</option>{branches.map((b) => <option key={b.id_sucursal} value={b.id_sucursal}>{b.nombre}</option>)}</select></label><input placeholder="Buscar SKU, carta o ID" value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && reload()} /><button onClick={reload}>Actualizar</button><a href="/" className="ghost">{brandText("Volver Shiny")}</a></section>
 {error && <div className="alert error">{error}</div>}{msg && <div className="alert ok">{msg}</div>}
 <nav>{[['inventario', 'Inventario'], ['pos', 'POS TCG'], ['mov', 'Movimientos'], ['scan', 'Escáner'], ['labels', 'Etiquetas'], ['count', 'Conteo'], ['bulk', 'Bulk']].map(([k, l]) => <button className={tab === k ? 'active' : ''} onClick={() => setTab(k)} key={k}>{l}</button>)}</nav>
 <main>
 {tab === 'inventario' && <><div className="actions"><button onClick={transfer}>Transferir</button><button onClick={() => exportKind('branchInventory')}>Exportar CSV</button></div><Table rows={inventory} cols={colsInv} /><p className="hint">Para ajustar: usa los botones de cada ID desde POS/escáner o selecciona una fila mediante el navegador. API disponible para operaciones bulk.</p></>}
 {tab === 'pos' && <div className="two"><section><h2>Inventario disponible</h2><Table rows={inventory} cols={[...colsInv.slice(0, 7), { k: 'id_inventario', l: 'Acción', f: (v, r) => <button disabled={!branch || Number(r.stock_sucursal) <= 0} onClick={() => addCart(r)}>Agregar</button> }]} /></section><aside><h2>Carrito</h2>{cart.map((x) => <div className="cart" key={x.idInventario}><span>{x.carta || x.sku}</span><input type="number" min="1" value={x.cantidad} onChange={(e) => setCart((c) => c.map((v) => v === x ? { ...v, cantidad: Number(e.target.value) } : v))} /><b>{money(x.precio * x.cantidad)}</b><button onClick={() => setCart((c) => c.filter((v) => v !== x))}>×</button></div>)}<div className="total">Total {money(total)}</div><button className="primary" onClick={sale} disabled={!cart.length || !branch}>Cobrar venta</button></aside></div>}
 {tab === 'mov' && <><div className="actions"><button onClick={transfer}>Nueva transferencia</button><button onClick={() => exportKind('movements')}>Exportar</button></div><Table rows={moves} cols={[{ k: 'fecha', l: 'Fecha', f: (v) => v ? new Date(v).toLocaleString() : '' }, { k: 'tipo', l: 'Tipo' }, { k: 'sku', l: 'SKU' }, { k: 'sucursal_origen', l: 'Origen' }, { k: 'sucursal_destino', l: 'Destino' }, { k: 'cantidad', l: 'Cant.' }, { k: 'referencia', l: 'Referencia' }]} /></>}
 {tab === 'scan' && <section className="panel"><h2>Escáner rápido</h2><p>{brandText("Compatible con lector USB/teclado y QR con contenido Shiny:TCG:<ID>. Si pegas el QR completo, se extrae el ID.")}</p><input autoFocus value={scan} onChange={(e) => setScan(e.target.value.replace(/^Shiny:TCG:/i, ''))} onKeyDown={(e) => e.key === 'Enter' && doScan('ENTRADA')} placeholder="Escanea SKU o ID inventario" /><div className="actions"><button onClick={() => doScan('ENTRADA')}>+ Entrada</button><button className="danger" onClick={() => doScan('SALIDA')}>− Salida</button></div></section>}
 {tab === 'labels' && <section className="panel"><h2>Etiquetas QR</h2><p>{brandText("Genera hasta 30 etiquetas de los resultados actuales. QR: Shiny:TCG:IDInventario.")}</p><button onClick={labels}>Generar / imprimir etiquetas</button><button onClick={() => exportKind('inventory')}>Exportar inventario</button></section>}
 {tab === 'count' && <><div className="actions"><button onClick={newCount} disabled={!branch}>Abrir conteo</button><input placeholder="ID conteo activo" value={countId} onChange={(e) => setCountId(e.target.value)} /><button onClick={capture} disabled={!countId}>Capturar variante</button><button onClick={closeCount} disabled={!countId}>Cerrar / conciliar</button></div><Table rows={counts} cols={[{ k: 'id_conteo', l: 'Conteo' }, { k: 'fecha_inicio', l: 'Inicio', f: (v) => v ? new Date(v).toLocaleString() : '' }, { k: 'sucursal', l: 'Sucursal' }, { k: 'estado', l: 'Estado' }, { k: 'variantes_contadas', l: 'Variantes' }, { k: 'diferencia_unidades', l: 'Diferencia' }, { k: 'ajustes_aplicados', l: 'Ajustes' }]} /></>}
 {tab === 'bulk' && <section className="panel"><h2>Importación / exportación masiva</h2><p>CSV para ajustes: <code>tipo,idInventario,idSucursal,delta,motivo</code>. Transferencias: <code>tipo,idInventario,idSucursalOrigen,idSucursalDestino,cantidad,motivo</code>.</p><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={(e) => importBulk(e.target.files?.[0])} /><div className="actions"><button onClick={() => exportKind('inventory')}>Inventario global</button><button onClick={() => exportKind('branchInventory')}>Inventario sucursales</button><button onClick={() => exportKind('movements')}>Movimientos</button><button onClick={() => exportKind('counts')}>Conteos</button><button onClick={() => exportKind('sales')}>Ventas</button></div></section>}
 </main><footer>{brandText("Shiny Fase Local 10.3 · POS TCG · movimientos · escáner · etiquetas · conteo · bulk")}</footer></div>;
}
